import sys
import time

a = 2
b = 0.2
c = 0.08
d = 1
def intro():
    print()
    print("(EVERYTHING IS DARK)")
    time.sleep(a)
    print("You slowly open your eyes and realize that you are in a car...your car...")
    time.sleep(a)
    print("As you start coming to your senses, you realize that you are soaked and covered with random debris.")
    time.sleep(a)
    print("You don't remember anything...")
    time.sleep(a)
    print("The crickets begin to chipper and the frogs begin to croak...")
    time.sleep(a)
    print("You unbuckle your seatbelt and leave your car from the passanger seat.")
    time.sleep(a)
    print("As you struggle to stand, you realize it's pitch black and the moon shines just enough to know that you are surrounded by trees.")
    time.sleep(a)
    print()
    print()
    question = '"Am I in a forest...?"'
    for character in question:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)
    print()
    print()
    print("You turn to your car and see that it's completely totaled and almost...")
    time.sleep(a)
    print("split in half...you shouldn't be alive...")
    time.sleep(a)
    print()
    print()
    print("You limp towards your car and open the passenger side door.")
    time.sleep(a)
    print("You find your cell phone underneath the passenger seat.")
    time.sleep(a)
    print("Fortunately the cell phone is still functional.")
    time.sleep(a)
    print()
    print()
    s1 = '"Damn, no signal..."'
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("As you put the cell phone into your pocket you hear footsteps quickly run towards you.")
    time.sleep(a)
    print()
    print()
    s2 = "'Who's th...'"
    for character in s2:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)   
    print()
    print()
    print("Before you could finish talking, someone hits the back of your head.")
    time.sleep(a)
    print("You're knocked out again...")
    time.sleep(a)
    print()
    print()
    print("You wake up in a cave with a lit fire pit.")
    time.sleep(a)
    print("You see the back of what appears to be a man.")
    time.sleep(a)
    print("He is preparing something over the fire but his body is blocking the view.")
    time.sleep(a)
    print("Your hands are tied behind your back...")
    time.sleep(a)
    print("You begin to panic.")
    time.sleep(a)
    print()
    print()
    print()
    print()
    print("You collect yourself momentarily")
    time.sleep(a)
    print("You begin trying to remove your bindings")
    time.sleep(a)
    print("You struggle with your bindings but to no avail...")
    time.sleep(a)
    print("The man hears your struggle, he begins to turn around.")
    time.sleep(a)
    print("You start fearing the worst")
    time.sleep(a)
    print()
    print()
    s1 = "'Please don't hurt me!'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("The man begins to walk towards you.")
    time.sleep(a)
    print("You notice he is far bigger than your average man.")
    time.sleep(a)
    print("you tremble as the man gets close to your face...The man takes a deep breath.")
    time.sleep(a)
    print("In a low and calming tone the man begins to speak.")
    time.sleep(a)
    print()
    print()       
    s2 = "'Now now...Try not to struggle.'"
    for character in s2:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    s3 = "'You are going to be a great sacrifice...'"
    for character in s3:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()       
    s4 = "'The gods will be pleased!'"
    for character in s4:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()      
    print("You are in shock, unable to speak.")
    time.sleep(a)
    print()
    print()                    
    print("As the man walks back to the fire pit you realize the bindings are loose enough to break free.")
    time.sleep(a)
    print("Option #1: Fight the man.")
    time.sleep(a)
    print("Option #2: Run away.")
    time.sleep(a)
    print("Option #3: Reason with the man.")
    time.sleep(a)
    print()
    print()
    choosePath = input("What should you do? (1/2/3): ")
    if choosePath == '1':
        print()
        path1()
    elif choosePath == '2':
        print()
        path2()
    elif choosePath == '3':
        print()
        path3()
                   
def path1():
    print("As the man walks towards the fire pit.")
    time.sleep(a)
    print("You jump on his back and wrap you arms around his neck into a choke hold.")
    time.sleep(a)
    print("The man yells.")
    time.sleep(a)
    print()
    print()    
    s1 = "'SILLY LAMB! YOU WILL DIE HERE!'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("The man takes the knife that was sitting next to the fire pit and stabs your thigh.")
    time.sleep(a)
    print("Despite being stabbed, you hold on tight to the choke hold.")
    time.sleep(a)
    print("As the man begins to faint he softly says.")
    time.sleep(a)
    print()
    print()
    s2 = "'You are not the first and the others will never see the light...'"
    for character in s2:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()   
    print("Option #1: Question the man.")
    time.sleep(a)
    print("Option #2: Render the man unconscious.")
    time.sleep(a)
    print("Option #3: Kill the man.")
    time.sleep(a)
    print()
    print()
    choosePath = input("What should you do? (1/2/3): ")
    if choosePath == '1':
        print()
        path1_1()
    elif choosePath == '2':
        print()
        path1_2()
    elif choosePath == '3':
        print()
        path1_3()        
        
def path1_1(): # DONE
    print("Before being completely knockedout from the choke hold.")
    time.sleep(a)
    print("You tie the man up and slap him until he wakes up.")
    time.sleep(a)
    print("You begin to question the man.")
    time.sleep(a)
    print()
    s1 = "'Hey! Wake up!'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    s2 = "'Are there more innocent people trapped here?!'"
    for character in s2:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print("The man looks at you with a smile and doesn't say a word")
    time.sleep(a)
    print("The silence helps you hear something. You hear faint cries for help")
    time.sleep(a)
    print("Using the flashlight from your phone you limp towards the noises.")
    time.sleep(a)
    print("You walk for what seems to be for hours and find people in a corner.")
    time.sleep(a)
    print("A boy and a girl and two pale lifeless bodies laying next to them")
    time.sleep(a)
    print("You noticed the phone has signal and desperately call the police.")
    time.sleep(a)
    print()
    print()
    policeCall()
    print()
    print()    
    print("As you start to speak, your vision starts to blur and your strength begins to fade.")
    time.sleep(a)
    print()
    print()
    s3 = "'We...are...trapped...cave...trees...there's a man...knife...kids...'"
    for character in s3:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    print("The wound from the knife lead to severe blood loss.")
    time.sleep(a)
    print("Before fading, you see the boy reach for the phone and speak the police.")
    time.sleep(a)
    print("The police are on the way and the kids will be saved.")
    time.sleep(a)
    print("As for you...")
    time.sleep(a)
    print("You died from the blood loss.")
    time.sleep(a)
    print()
    thanks()       

def path1_2(): #DONE
    print("You hold the choke hold until the body of the man goes limp.")
    time.sleep(a)
    print("you catch your breathe and look over the fire pit and notice there was a knife and some sort of hand made relics.")
    time.sleep(a)
    print()
    print()
    s1 = "'What the hell are these...'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("You hear noises coming from deeper of the cave.")
    print()
    print()   
    print("Option #1: Investigate.")
    time.sleep(a)
    print("Option #2: Run away.")
    time.sleep(a)
    print("Option #3: Study the artifacts.")
    time.sleep(a)
    print()
    print()
    choosePath = input("What should you do? (1/2/3): ")
    if choosePath == '1':
        print()
        path1_2_a()
    elif choosePath == '2':
        print()
        path1_2_b()
    elif choosePath == '3':
        print()
        path1_2_c()    

def path1_2_a(): # DONE
    print("You take out your cell phone to use as a flash light and begin to walk towards the sounds.")
    time.sleep(a)
    print("You walk what seems to be miles into a dark corner of the cave.")
    time.sleep(a)
    print("You flash the light where the sound is coming from.")
    time.sleep(a)
    print("You can't believe your eyes...")
    time.sleep(a)
    print("It's a boy and a girl along with 2 dead bodies next to them.")
    time.sleep(a)
    print()
    print()
    s1 = "'Oh god... are you both okay?!'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("They both nod their heads.")
    time.sleep(a)
    print("You notice that your cell phone has signal and you call the police.")
    time.sleep(a)
    print()
    print()
    policeCall()
    print()
    print()
    print("hours pass by and the police arrive and arrest the man.")
    time.sleep(a)
    print("The medics take the kids and examine the dead bodies.")
    time.sleep(a)
    print("Turns out the man was a delusioned serial killer.")
    time.sleep(a)
    print()
    print()
    print("You survived.")
    time.sleep(a)
    thanks()

def path1_2_b(): #DONE
    print("the man begins to wake up and begins to break free.")
    time.sleep(a)
    print("You decide to make a break for it and run out of the cave.")
    time.sleep(a)
    print("You take out your cell phone to use as a light and notice you have signal.")
    time.sleep(a)
    print("You call the police.")
    time.sleep(a)
    print()
    print()
    policeCall()
    print()
    print()
    print("Out of breath you start telling the police everything.")
    time.sleep(a)
    print()
    print()
    s1 = "'Help! I'm in a forest and was att...'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)        
    print()
    print()
    print("While you were running and talking, you tripped over a rock and fell over a hill.")
    time.sleep(a)
    print("As you are rolling down the hill, hitting everything on the way down.")
    time.sleep(a)
    print("You split you head open on a rock face down in a puddle.")
    time.sleep(a)
    print("You died by either the impact or by drowning.")
    time.sleep(a)
    print()
    print()
    thanks()

def path1_2_c(): # DONE
    print("You look closer to the relics by the fire pit.")
    time.sleep(a)
    print("You start to hear whispers coming from the relics.")
    time.sleep(a)
    print()
    print()
    s1 = "'Wear me...give in...kill them...'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)        
    print()
    print()
    print("You carefully wear the relic around your neck.")
    time.sleep(a)
    print("The necklace quickly tightens around your neck.")
    time.sleep(a)
    print()
    print("The voices continue, now clear instead of whispers.")
    time.sleep(a)
    print()
    print()
    s2 = "'You serve the dark brotherhood now...'"
    for character in s2:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)
    print()
    print()
    s3 = "'There's some children in the back of this cave. Sacrifice them to me.'"
    for character in s3:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)
    print()
    print()
    print("Your body is moving on it's own. Like you are being controlled.")
    time.sleep(a)
    print("You pick up the knife and head to the back of the cave...")
    time.sleep(a)
    print("You are now a servant...")
    time.sleep(a)
    print()
    print()
    thanks()

def path1_3():  # DONE
    print("Pumping with adrenaline, you decide to continue the chokehold with the intent to kill.")
    time.sleep(a)
    print("Suddenly, the necklace the man was wearing was starting to get hot while pressed on your skin.")
    time.sleep(a)
    print("The necklace burns you. Forcing you to let go and the man wakes up.")
    time.sleep(a)
    print("The man gets up.")
    time.sleep(a)   
    print()
    print()    
    s1 = "'It seems I won't be the one dying tonight. I live and breath for the gods!'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("It's now a kill or be killed situation...")
    time.sleep(a) 
    print()
    print() 
    print("Option #1: Grab rock.")
    time.sleep(a)
    print("Option #2: Grab knife.")
    time.sleep(a)
    print("Option #3: Pocket sand!.")
    time.sleep(a)
    print()
    print()
    choosePath = input("What should you do? (1/2/3): ")
    if choosePath == '1':
        print()
        path1_3_a()
    elif choosePath == '2':
        print()
        path1_3_b()
    elif choosePath == '3':
        print()
        path1_3_c()

def path1_3_a(): # DONE
    print("You quickly get up and frantically look for a weapon to use.")
    time.sleep(a)
    print()
    print()
    print("You see a pile of rocks and a knife by the fire.")
    time.sleep(a)
    print("You completely ignore the knife and grabbed a rock.")
    time.sleep(a)
    print("You swing as hard as you can with the rock in your hand striking the man on the side of head.")
    time.sleep(a)
    print("The rock falls apart on impact due to the mans thick skull.")
    time.sleep(a)
    print("The man grabs you, throws you around like a piece of paper and finally ending your life by snapping your neck.")
    time.sleep(a)
    print()
    print()
    thanks()

def path1_3_b(): #DONE
    print("You quickly get up and frantically look for a weapon to use.")
    time.sleep(a)
    print()
    print()
    print("You see a pile of rocks and a knife by the fire.")
    time.sleep(a)
    print("It's obviously a no brainer and you pick up the knife.")
    time.sleep(a)
    print("As you ready your self in what seems to be an amateur knife fight stance, the man also pulls out a bigger knife.")
    time.sleep(a)
    print("The man rushes you with full force.")
    time.sleep(a)
    print("You freeze in place and get stabbed right in the heart.")
    time.sleep(a)
    thanks()

def path1_3_c(): # DONE
    print("You quickly get up and frantically look for a weapon to use.")
    time.sleep(a)
    print()
    print()
    print("You see a pile of rocks and a knife by the fire.")
    time.sleep(a)
    print("But you decide to grab some dirt and place it in your pocket.")
    time.sleep(a)
    print("You get up and act as if you are going to wrestle the man.")
    time.sleep(a)
    print("As the man rushes towards you, you grab the dirt that's in your pocket and throw into his eyes.")
    time.sleep(a)
    print()
    print()    
    s1 = "'POCKET SAND!'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("Blinding the man, you decide to push him and he lands over the fire, buring the man alive.")
    time.sleep(a)
    print()
    print()
    print("You escape and call the police.")
    time.sleep(a)
    print()
    print()
    policeCall()
    print()
    print()
    thanks()

def path2(): # DONE
    print("You get up and push the man into the fire pit.")
    time.sleep(a)
    print("The man falls in and catches fire.")
    time.sleep(a)
    print("He begins to yell.")
    time.sleep(a)
    print()
    print()
    s1 = "'AAARRRGH! AAAAH!'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)        
    print()
    print()
    print("In the midst of it all you decide to make a break for it and run out of the cave.")
    time.sleep(a)
    print("You take out your cell phone to use as a light and notice you have signal.")
    time.sleep(a)
    print("You call the police.")
    time.sleep(a)
    print()
    print()
    policeCall()
    print()
    print()
    print("Out of breath you start telling the police everything.")
    time.sleep(a)
    print()
    print()
    s2 = "'Help! I'm in a forest and was att...'"
    for character in s2:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("While you were running and talking, you tripped over a rock and fell over a hill.")
    time.sleep(a)
    print("As you are rolling down the hill, hitting everything on the way down.")
    time.sleep(a)
    print("You split your head open on a rock face down in a puddle.")
    time.sleep(a)
    print("You died from either by impact or by drowning.")
    time.sleep(a)
    print()
    print()
    thanks()

def path3():
    print("You try to reason with the man.")
    print()
    print()       
    s1 = "'This is wrong! I did nothing to you!'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("The man chuckles.")
    print()
    print()       
    s2 = "'It does not matter! All that matters is that you will be dead soon and I will have pleased the gods!'"
    for character in s2:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("Option #1: I have a family.")
    time.sleep(a)
    print("Option #2: Convince you are family.")
    time.sleep(a)
    print("Option #3: Threaten.")
    time.sleep(a)
    print()
    print()
    choosePath = input("What should you do? (1/2/3): ")
    if choosePath == '1':
        print()
        path3_1_a()
    elif choosePath == '2':
        print()
        path3_1_b()
    elif choosePath == '3':
        print()
        path3_1_c()   

def path3_1_a(): #DONE
    s1 = "'Please don't do this, I have a family...A wife and 2 kids!'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    s2 = "'I need to get get back to them!'"
    for character in s2:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("As you try to reason with the man, the man smiles at you...")
    time.sleep(a)
    print()
    print()
    s3 = "'Oh, you have a familiy?'"
    for character in s3:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()    
    s4 = "'I have one too. Do you want to see them?'"
    for character in s4:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("The man grabs you and takes you to the back of the cave")
    time.sleep(a)
    print("For what seems to be a mile, you reach the end of the cave.")
    time.sleep(a)
    print("You see two lifeless bodies and two live children in the corner.")
    time.sleep(a)
    print()
    print()
    s5 = "'Now you get to join my family'"
    for character in s5:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)
    print()
    print()
    print("The man grabs your head and snaps your neck...")
    time.sleep(a)
    print()
    print()
    thanks()


def path3_1_b():
    print("You try to convince the man that you are his relative.")
    time.sleep(a)
    print("You gather the courage to sound angry at the man.")
    time.sleep(a)
    print()
    print()       
    s1 = "'You know our mother wouldn't be proud...'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()       
    s2 = "'You know our mother wouldn't be proud...'"
    for character in s2:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("The man widens his eyes.")
    time.sleep(a)
    print()
    print()       
    s3 = "'Don't you try to fool me, imposter!'"
    for character in s3:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("The man looks unsure and confused, you decide to take advantage.")
    time.sleep(a)
    print()
    print()       
    s4 = "'How can I prove that you are my brother?'"
    for character in s4:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("The man gives an evil smirk.")
    time.sleep(a)
    print()
    print()
    s5 = "'Come follow me...'"
    for character in s5:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("You and the man make way to the back of the cave.")
    time.sleep(a)
    print("As you get closer to the back you hear sniffles and cries from two young children.")
    time.sleep(a)
    print()
    print()
    s6 = "'I can not bare to sacrifice these children, mother did say I have a soft spot for children but mother told me stories about you...'"
    for character in s6:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)
    print()
    print()
    s7 = "'Your bloodlust does not discriminate...Sacrifce them!'"
    for character in s7:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)
    print()    
    print()
    print("Option #1: Sacrifice the children.")
    time.sleep(a)
    print("Option #2: Don't sacrifice the children.")
    time.sleep(a)
    print()
    print()
    choosePath = input("What should you do? (1/2/3): ")
    if choosePath == '1':
        print()
        path3_1_a1()
    elif choosePath == '2':
        print()
        path3_1_b2()

def path3_1_a1():
    print("The man throws locks you behind a door with the children.")
    time.sleep(a) 
    print("You see a knife on the floor.")
    time.sleep(a) 
    print("Fearing for own life, you decide to grab the knife and walk towards the children.")
    time.sleep(a)
    print()
    print()
    s1 = "'I'm sorry...I'm so sorry...'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)
    print()    
    print()
    print("The deed is done and you start to go insane from what you've just done.")
    time.sleep(a)
    print()
    print()
    thanks()

def path3_1_b2():
    print("The man throws locks you behind a door with the children.")
    time.sleep(a) 
    print("You see a knife on the floor.")
    time.sleep(a) 
    print("You refuse to grab the knife...")
    time.sleep(a)
    print()
    print()
    print("One of the children rush you and grabs your legs while the other one grabs the knife and stabs your chest...")
    time.sleep(a)
    print("The children begin to laugh as you collapse to the ground.")
    time.sleep(a)
    print()
    print()
    s1 = "'The sacrifice is complete!'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)
    print()    
    print()
    thanks()

def path3_1_c():
    print("You threaten to call the police.")
    time.sleep(a)
    print()
    print()       
    s1 = "'If you don't let me go I will call the police!'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("The man chuckles.")
    time.sleep(a)
    print()
    print()       
    s2 = "'Go ahead, call the police.'"
    for character in s2:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(d)    
    print()
    print()
    print("As you reach for your phone to call the police the man grabs your neck and strangles you to death.")
    time.sleep(a)
    print()
    print()
    thanks()
               
def policeCall():
    s1 = "'Hello, this is 911. What's the emergency?'"
    for character in s1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b) 

def thanks():
    print("Thanks for playing!")
    time.sleep(a)
# Main Function ###

print()
print()
print("     ######################")
print("     |                    |")
print("     |      Survive       |")
print("     |                    |")
print("     ######################")
print()
print()
time.sleep(a)
print("Wha... What happened? What just happened?")
time.sleep(a)
print("My head is killing me...")
time.sleep(a)
print()
startGame = input("Would you like to start the game? (Y/N): ")
if startGame == "n" or startGame == "N": # Easier to have y/Y vs yes and no.
    print("Maybe next time")
    time.sleep(3)
elif startGame == "y" or startGame == "Y":
    intro()